### ISSUE TITLE
When "edit":false, can break blocks, cannot place blocks.

### ISSUE THREAD

**Issue by markkrueg** [LDX-MCPE/iProtector#27]
I have a fresh world. Spawn protection is set to 0. I am not op. I am not "bob". The config.yml file is set to defaults.This is my areas.json:
```
[{"name":"test","flags":{"edit":false,"god":true,"touch":true},"pos1":[137,1,162],"pos2":[153,127,172],"level":"world","whitelist":["bob"]}]
```

When standing at 143, 67, 164 I am able to break blocks. I am not able to PvP. I am not able to place blocks.

I should not be able to break blocks when edit is false; right?

```
# Config file for iProtector by LDX;

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  world:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false
```
